#!/usr/bin/env python3
"""Bundle the REAL scene sources + the castcheck shims + a runner into one
Luau file, so a shot's own camera and a shot's own set can be dumped headlessly.

`opening` bundles the North Pole cinematic (Env/Cast/Sequences/Camera);
`menu` bundles the welcome screen's hangar (MenuScene + what it requires).
"""
import pathlib, sys

here = pathlib.Path(__file__).resolve().parent
root = here.parent.parent
castcheck = root / "tools/castcheck"

SETS = {
    "opening": (["Signal", "Config", "Palette", "Settings", "Kit", "VehicleMotion",
                 "GlyphLanguage", "Instrumentation", "Env", "CharacterAppearance", "Cast", "Lighting",
                 "PerformanceDirector", "Camera", "Sequences"], "dump.luau"),
    "menu": (["Signal", "Config", "Palette", "AegisRig", "Responsive", "Settings",
              "MenuScene"], "menu.luau"),
    # Every human in the opening, on a neutral stage. See lineup.luau.
    "lineup": (["Signal", "Config", "Palette", "Settings", "Kit", "VehicleMotion",
                "GlyphLanguage", "Instrumentation", "Env", "CharacterAppearance", "Cast", "Lighting",
                "PerformanceDirector", "Camera", "Sequences"], "lineup.luau"),
}
PATHS = {
    "Signal": "src/shared/Signal.lua", "Config": "src/shared/Config.lua",
    "Palette": "src/shared/Palette.lua", "AegisRig": "src/shared/AegisRig.lua",
    "Settings": "src/client/Settings.lua", "Responsive": "src/client/Responsive.lua",
    "MenuScene": "src/client/MenuScene.lua", "Kit": "src/client/NorthPole/Kit.lua",
    "Env": "src/client/NorthPole/Env.lua", "Cast": "src/client/NorthPole/Cast.lua",
    "Lighting": "src/client/NorthPole/Lighting.lua",
    "PerformanceDirector": "src/client/NorthPole/PerformanceDirector.lua",
    "Camera": "src/client/NorthPole/Camera.lua",
    "VehicleMotion": "src/client/NorthPole/VehicleMotion.lua",
    "CharacterAppearance": "src/client/NorthPole/CharacterAppearance.lua",
    "Sequences": "src/client/NorthPole/Sequences.lua",
    "GlyphLanguage": "src/client/NorthPole/GlyphLanguage.lua",
    "Instrumentation": "src/client/NorthPole/Instrumentation.lua",
}

which = sys.argv[1] if len(sys.argv) > 1 else "opening"
modules, runner = SETS[which]

out = ["--!nonstrict\n-- GENERATED by tools/scenecheck/build.py - do not edit.\n"]
out.append("local Shim=(function()\n%s\nend)()\n" % (root / "tools/phase0a/offline/shim.luau").read_text())
out.append("Vector3={new=Shim.V3,zero=Shim.V3(0,0,0),one=Shim.V3(1,1,1),"
           "xAxis=Shim.V3(1,0,0),yAxis=Shim.V3(0,1,0),zAxis=Shim.V3(0,0,1)}\n"
           "CFrame=Shim.CFrame\nColor3=Shim.Color3\n")
out.append("local RBX=(function()\n%s\nend)()\n" % (castcheck / "roblox.luau").read_text())
out.append("""
Enum=RBX.Enum
Vector2=RBX.Vector2
UDim2=RBX.UDim2
NumberRange=RBX.NumberRange
NumberSequence=RBX.NumberSequence
NumberSequenceKeypoint=RBX.NumberSequenceKeypoint
ColorSequence=RBX.ColorSequence
RaycastParams=RBX.RaycastParams
OverlapParams=RBX.OverlapParams
Random=RBX.Random
Instance=RBX.Instance
workspace=RBX.workspace
game=RBX.game
warn=RBX.warn
TweenInfo={new=function() return {} end}
task={wait=function() end,delay=function() end,spawn=function() end,defer=function() end,cancel=function() end}
-- Services the cinematic never touches but the menu scene does.
RBX.extraServices={
 UserInputService={TouchEnabled=false,KeyboardEnabled=true,GamepadEnabled=false,MouseEnabled=true,
  LastInputTypeChanged={Connect=function() return {Disconnect=function() end} end},
  GetLastInputType=function() return {Name="MouseMovement"} end},
 GuiService={GetGuiInset=function() return RBX.Vector2.new(0,36) end,
  MenuOpened={Connect=function() return {Disconnect=function() end} end}},
 ContextActionService={BindAction=function() end,UnbindAction=function() end},
 SoundService={},
 Debris={AddItem=function() end},
 CollectionService={GetTagged=function() return {} end,
  GetInstanceAddedSignal=function() return {Connect=function() return {Disconnect=function() end} end} end},
}
local MOD={}
local ParentProxy
ParentProxy=setmetatable({},{__index=function(_,k)
 if k=="Parent" then return ParentProxy end
 return {__mod=k}
end})
local function req(t)
 local key=t.__mod or rawget(t,"__mod")
 assert(key,"unresolvable require in bundle")
 local m=MOD[key]
 assert(m,"module not bundled: "..tostring(key))
 return m
end
local rawTypeof=typeof
typeof=function(value)
 if type(value)=="table" then
  local meta=getmetatable(value)
  if meta==Shim.Vector3Meta then return "Vector3" end
  if meta==Shim.CFrameMeta then return "CFrame" end
  if rawget(value,"ClassName")~=nil then return "Instance" end
 end
 return rawTypeof(value)
end
""")
out.append("RBX.install({%s})\n" % ",".join("%s=true" % name for name in modules))
for name in modules:
    body = (root / PATHS[name]).read_text()
    out.append("MOD.%s=(function()\nlocal script={Parent=ParentProxy}\nlocal require=req\n%s\nend)()\n" % (name, body))
out.append((here / runner).read_text())

target = here / f"{which}.generated.luau"
target.write_text("".join(out))
print(target)
