#!/usr/bin/env python3
"""Bundle src/shared/Human/*.lua + the shim + a runner into one Luau file."""
import pathlib,sys
here=pathlib.Path(__file__).resolve().parent
root=here.parent.parent.parent
src=root/"src/shared/Human"
order=["Skeleton","Pose","Locomotion","Actor","Validate","Build"]
runner=here/(sys.argv[1] if len(sys.argv)>1 else "run.luau")
out=[]
out.append("--!nonstrict\n-- GENERATED by tools/phase0a/offline/build.py - do not edit.\n")
out.append("local Shim=(function()\n%s\nend)()\n"%(here/"shim.luau").read_text())
out.append("Vector3={new=Shim.V3}\nCFrame=Shim.CFrame\nColor3=Shim.Color3\n")
out.append("local MOD={}\n")
out.append("local ParentProxy=setmetatable({},{__index=function(_,k) return {__mod=k} end})\n")
out.append("local function req(t) return MOD[t.__mod] end\n")
for name in order:
    body=(src/f"{name}.lua").read_text()
    out.append("MOD.%s=(function()\nlocal script={Parent=ParentProxy}\nlocal require=req\n%s\nend)()\n"%(name,body))
out.append("MOD.Timeline=(function()\n%s\nend)()\n"%(here.parent/"Timeline.lua").read_text())
out.append("MOD=MOD\n")
out.append(runner.read_text())
target=here/"bundle.generated.luau"
target.write_text("".join(out))
print(target)
