#!/usr/bin/env python3
"""Bundle the REAL NorthPole rig sources + shims + a runner into one Luau file."""
import pathlib,sys
here=pathlib.Path(__file__).resolve().parent
root=here.parent.parent
out=[]
out.append("--!nonstrict\n-- GENERATED by tools/castcheck/build.py - do not edit.\n")
out.append("local Shim=(function()\n%s\nend)()\n"%(root/"tools/phase0a/offline/shim.luau").read_text())
# Vector3.zero/one are real constants Camera.lua relies on, not just .new.
out.append("Vector3={new=Shim.V3,zero=Shim.V3(0,0,0),one=Shim.V3(1,1,1),xAxis=Shim.V3(1,0,0),yAxis=Shim.V3(0,1,0),zAxis=Shim.V3(0,0,1)}\nCFrame=Shim.CFrame\nColor3=Shim.Color3\n")
out.append("local RBX=(function()\n%s\nend)()\n"%(here/"roblox.luau").read_text())
out.append("""
Enum=RBX.Enum
Vector2=RBX.Vector2
UDim2=RBX.UDim2
NumberRange=RBX.NumberRange
NumberSequence=RBX.NumberSequence
NumberSequenceKeypoint=RBX.NumberSequenceKeypoint
ColorSequence=RBX.ColorSequence
RaycastParams=RBX.RaycastParams
OverlapParams=RBX.OverlapParams
Random=RBX.Random
Instance=RBX.Instance
workspace=RBX.workspace
game=RBX.game
warn=RBX.warn
local MOD={}
-- script.Parent.X and script.Parent.Parent.X both have to resolve; "Parent"
-- returns the proxy again, anything else is a module name.
local ParentProxy
ParentProxy=setmetatable({},{__index=function(_,k)
 if k=="Parent" then return ParentProxy end
 return {__mod=k}
end})
local function req(t)
 local key=t.__mod or rawget(t,"__mod")
 assert(key,"unresolvable require in bundle")
 local m=MOD[key]
 assert(m,"module not bundled: "..tostring(key))
 return m
end
-- Roblox's typeof() over the shim types: Camera.lua and Sequences.lua both
-- branch on typeof(x)=="Vector3" / "Instance", so a plain Lua type() would
-- send every shot down the wrong path.
local rawTypeof=typeof
typeof=function(value)
 if type(value)=="table" then
  local meta=getmetatable(value)
  if meta==Shim.Vector3Meta then return "Vector3" end
  if meta==Shim.CFrameMeta then return "CFrame" end
  if rawget(value,"ClassName")~=nil then return "Instance" end
 end
 return rawTypeof(value)
end
""")
# Order matters: dependencies first.
sources=[
 ("Signal","src/shared/Signal.lua"),
 ("Config","src/shared/Config.lua"),
 ("Palette","src/shared/Palette.lua"),
 ("Settings","src/client/Settings.lua"),
 ("Kit","src/client/NorthPole/Kit.lua"),
 ("Env","src/client/NorthPole/Env.lua"),
 ("Cast","src/client/NorthPole/Cast.lua"),
 ("Lighting","src/client/NorthPole/Lighting.lua"),
 ("PerformanceDirector","src/client/NorthPole/PerformanceDirector.lua"),
 ("Camera","src/client/NorthPole/Camera.lua"),
 ("Sequences","src/client/NorthPole/Sequences.lua"),
]
out.append("RBX.install({%s})\n"%",".join("%s=true"%name for name,_ in sources))
for name,rel in sources:
    body=(root/rel).read_text()
    out.append("MOD.%s=(function()\nlocal script={Parent=ParentProxy}\nlocal require=req\n%s\nend)()\n"%(name,body))
runner=here/(sys.argv[1] if len(sys.argv)>1 else "run.luau")
out.append(runner.read_text())
target=pathlib.Path(sys.argv[2]) if len(sys.argv)>2 else here/"bundle.generated.luau"
target.parent.mkdir(parents=True,exist_ok=True)
target.write_text("".join(out))
print(target)
